const db = window.supabaseClient;

async function generateBahpe(packageId) {
    try {

        const { data: pkg, error: pkgError } =
            await db
                .from('packages')
                .select('*')
                .eq('id', packageId)
                .single();

        if (pkgError) throw pkgError;

        const { data: hps, error: hpsError } =
            await db
                .from('package_hps')
                .select('*')
                .eq('package_id', packageId)
                .single();

        if (hpsError) throw hpsError;

        const { data: existing } =
            await db
                .from('package_bahpe')
                .select('id')
                .eq('package_id', packageId)
                .maybeSingle();

        if (existing) {
            alert('BAHPE sudah pernah dibuat');
            return;
        }

        const { error: insertError } =
            await db
                .from('package_bahpe')
                .insert({
                    tenant_id: pkg.tenant_id,
                    package_id: pkg.id,
                    document_date: new Date().toISOString().split('T')[0],
                    hps_amount: hps.total_hps,
                    preparation_notes: 'BAHPE generated by SIDEVA9',
                    generated_at: new Date().toISOString()
                });

        if (insertError) throw insertError;

        const { error: statusError } =
            await db
                .from('packages')
                .update({
                    package_status: 'BAHPE_DRAFT'
                })
                .eq('id', packageId);

        if (statusError) throw statusError;

        alert('BAHPE berhasil dibuat');

        return true;

    } catch (err) {

        console.error(err);

        alert(
            err.message ||
            'Gagal membuat BAHPE'
        );

        return false;
    }
}

async function approveBahpe(bahpeId) {
    try {

        const user =
            window.currentUser || {};

        const { data: bahpe, error: bahpeError } =
            await db
                .from('package_bahpe')
                .select('*')
                .eq('id', bahpeId)
                .single();

        if (bahpeError) throw bahpeError;

        const { error: approveError } =
            await db
                .from('package_bahpe')
                .update({
                    approved_at: new Date().toISOString(),
                    approved_by: user.id || null
                })
                .eq('id', bahpeId);

        if (approveError) throw approveError;

        const { error: statusError } =
            await db
                .from('packages')
                .update({
                    package_status: 'BAHPE_COMPLETE'
                })
                .eq('id', bahpe.package_id);

        if (statusError) throw statusError;

        alert('BAHPE berhasil disetujui');

        return true;

    } catch (err) {

        console.error(err);

        alert(
            err.message ||
            'Gagal approve BAHPE'
        );

        return false;
    }
}

async function submitToPBJ(packageId) {
    try {

        const { error } =
            await db
                .from('packages')
                .update({
                    package_status: 'READY_PROCUREMENT'
                })
                .eq('id', packageId);

        if (error) throw error;

        alert('Paket siap diserahkan ke PBJ');

        return true;

    } catch (err) {

        console.error(err);

        alert(
            err.message ||
            'Gagal menyerahkan ke PBJ'
        );

        return false;
    }
}

async function getBahpeList() {

    const { data, error } =
        await db
            .from('package_bahpe')
            .select(`
                *,
                packages(
                    package_name,
                    fiscal_year,
                    package_status
                )
            `)
            .order(
                'created_at',
                { ascending: false }
            );

    if (error) {
        console.error(error);
        return [];
    }

    return data || [];
}

window.generateBahpe = generateBahpe;
window.approveBahpe = approveBahpe;
window.submitToPBJ = submitToPBJ;
window.getBahpeList = getBahpeList;
